$(document).ready(function(){
	$(".slaider-team").owlCarousel({
    loop:false,
    margin: 20,
    nav:true,
    autoHeight:true,
    navText:false,
        responsive:{
            0:{
                items:1
            },
            600:{
                items:1
            },
            1000:{
                items:3
            }
        }  
	});
	$(".slaider").owlCarousel({
    loop:false,
    margin:10,
    nav:true,
    autoHeight:true,
    dots:false,
    navText:false,
        responsive:{
            0:{
                items:1
            },
            600:{
                items:1
            },
            1000:{
                items:6
            }
        }  
	});

	$(".slaider-1").owlCarousel({
    loop:false,
    margin:10,
    nav:true,
    autoHeight:true,
    navText:false,
        responsive:{
            0:{
                items:1
            },
            600:{
                items:1
            },
            1000:{
                items:7
            }
        }  
	});

  	$(".slaider-2").owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    autoHeight:true,
    navText:false,
        responsive:{
            0:{
                items:1
            },
            600:{
                items:1
            },
            1000:{
                items:2
            }
        }  
	});

});